---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tanzu-go
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/workload-type: web
  name: tanzu-go
spec:
  build:
    env:
    - name: BP_GO_VERSION
      value: 1.20.1
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8000
      name: http
  - name: annotations
    value:
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "10"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/max-scale: "5"
      autoscaling.knative.dev/min-scale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/kubeages/tanzu-go.git